### PR TITLE
Remove redundant VXG player & related webtv functionality (saving ~2.5MB)

### PR DESCRIPTION
**Pull request by wedebe**
Remove redundant VXG player & related webtv functionality (saving ~2.5MB)

This change:
Removes VXG player & related webtv functionality,
reducing image size by approx 2.5MB.

The technology upon which vxg relied was removed from browsers several years ago and no suitable alternative has been found.

"On 12 October 2016, a comment on the Chromium issue tracker indicated that Google's Pepper and Native Client teams had been destaffed.[7] On 30 May 2017, Google announced deprecation of PNaCl in favor of WebAssembly.[8] Although initially Google planned to remove PNaCl in first quarter of 2018,[8] and later in the second quarter of 2019,[9]
it has been removed in June 2022 (together with Chrome Apps).[10][11]"
https://en.wikipedia.org/wiki/Google_Native_Client

The original (V1) version of OpenWebif is no longer in active development and will continue to contain the VXG plugin and webtv code for those tempted to use an unsupported browser version combined with command-line hacks, but there is absolutely no suggestion that this might even work, and no support will be provided!
https://github.com/E2OpenPlugins/e2openplugin-OpenWebif

Alternatives to consider are IINA Media Player on Mac; dreamDroid/dreamPlayer/dreamEPG on Android; VLC/Kodi on all platforms*.
* These are merely suggestions, not endorsements

### CODE REVIEW

**Comment by jbleyel** [comment]
VXG player is a separate ipk .. so no need to do anything.

**Comment by wedebe** [comment]
> VXG player is a separate ipk .. so no need to do anything.

Ah, should I revert the `vxg` folder deletion to avoid conflict?

All other files and logic should still be removed for cleanliness.

**Comment by jbleyel** [comment]
You have only the vxg folder if you have installed the extra ipk or if you copy all from git.

**Comment by wedebe** [comment]
> You have only the vxg folder if you have installed the extra ipk or if you copy all from git.

Will the VXG plugin be removed from the build process for oe-alliance/OpenWebif?

**Comment by jbleyel** [comment]
> > You have only the vxg folder if you have installed the extra ipk or if you copy all from git.
> 
> Will the VXG plugin be removed from the build process for oe-alliance/OpenWebif?

Yes .. it's a split function to separate these 3 packages.

enigma2-plugin-extensions-openwebif
enigma2-plugin-extensions-openwebif-themes
enigma2-plugin-extensions-openwebif-vxg

**Pull request closed without merging**
