### PR TITLE
Replaced modern css with sass and removed duplicate styles

### PR DESCRIPTION
**Pull request by t5k6**

### CODE REVIEW

**Comment by jbleyel** [comment]
Have you tested the build script?
It’s the first part of this file till the git commit.


https://github.com/oe-alliance/OpenWebif/blob/main/CI/npm.sh

**Comment by t5k6** [comment]
Admittedly, I haven't; I only checked the build-css script. As it turns out there's a slight incompatibility with the classic-css build.
I have a fix ready, but before submitting it, would it be okay if I:
1. Reduced package dependencies?
2. Further eliminated CSS duplication by combining and converting files in the modern/css folder?

**Comment by jbleyel** [comment]
The build script is now failing.

Please check the log and fix it.

https://github.com/oe-alliance/OpenWebif/actions/runs/12015741510/job/33494451596

**Comment by jbleyel** [comment]
I have fixed the classic build.
But I donno if the modern build is working.

**Pull request merged**
